# Generated by Django 2.1.7 on 2019-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('foto_employee', models.ImageField(default='', upload_to='static/images/')),
            ],
            options={
                'verbose_name': 'Информация о сотруднике',
                'verbose_name_plural': 'Информация о сотрудниках',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Должность сотрудника',
                'verbose_name_plural': 'Должности сотрудников',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='catalog.Position'),
        ),
    ]
